app:
  report_date: "2026-09-30"
  dry_run: true

livedune:
  base_url: "https://api.livedune.com/accounts"
  token: LIVEDUNE_API_TOKEN
  account_dict:
    "ВК": 3453313
    "МАХ": 3369918
    "Телеграм": 3050607

google:
  google_sheet_url: "https://docs.google.com/spreadsheets/d/1YRn7y_pTmBcj9YGCXSPX1SnQRulvFgR59PKn8NB6yMw"
  worksheet_name: "auto_table"
  worksheet_id: "1212522662"
  credentials_path: "statics/credentials.json"
  scope: ['https://spreadsheets.google.com/feeds',
          'https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive.file',
          'https://www.googleapis.com/auth/drive' ]

yandex:
  base_url: "https://ord.yandex.net/api/v8"
  token: YANDEX_ORD_OAUTH_TOKEN
  timeout_seconds: 30
  platform_dict:
    "ВК": "c2dEzzKA3ZjtSewXRvQ5Ao"
    "МАХ": "qG9XK9A9nxLdrqgEumzNLy"
    "Телеграм": "MbbgH4gydcfc5gf647uoFP"
  endpoints:
    statistics: "/api/{api_version}/statistics"
    status: "/api/{api_version}/status"
